return {
    "nvim-treesitter/nvim-treesitter",
    version = false,
    build = ":TSUpdate",
    event = { "BufReadPost", "BufNewFile" },
    opts = {
        sync_install = false,
        ignore_install = { "javascript" },
        highlight = {
            enable = true,
            additional_vim_regex_highlighting = false,
        },
        indent = { enable = true },
        auto_install = true,
        ensure_installed = {
            "bash",
            "c",
            "go",
            "gomod",
            "gosum",
            "gowork",
            "hcl",
            "helm",
            "html",
            "javascript",
            "json",
            "lua",
            "luadoc",
            "luap",
            "query",
            "regex",
            "rust",
            "terraform",
            "vim",
            "vimdoc",
            "yaml",
        },
        incremental_selection = {
            enable = true,
            keymaps = {
                init_selection = "<leader>vv",
                node_incremental = "+",
                scope_incremental = false,
                node_decremental = "_",
            },
        },
    },
}
