#!/usr/bin/env bash

source "$CONFIG_DIR/colors.sh"

PLUGIN_DIR="$CONFIG_DIR/plugins"

##### Bar Appearance #####
# For all options see:
# https://felixkratz.github.io/SketchyBar/config/bar
# https://felixkratz.github.io/SketchyBar/config/tricks
# https://felixkratz.github.io/SketchyBar/config/items

sketchybar --bar position=top height=25 blur_radius=30 color=0x40000000

##### Setting defaults #####

defaults=(
  padding_left=2
  padding_right=2
  icon.font="MesloLGS NF:Bold:14.0"
  label.font="MesloLGS NF:Bold:12.0"
  icon.color=$WHITE
  label.color=$WHITE
  icon.padding_left=4
  icon.padding_right=4
  label.padding_left=4
  label.padding_right=4

  popup.background.border_width=2
  popup.background.corner_radius=9
  popup.background.border_color=$POPUP_BORDER_COLOR
  popup.background.color=$POPUP_BACKGROUND_COLOR
  popup.blur_radius=20
  popup.background.shadow.drawing=on

)
sketchybar --default "${defaults[@]}"

##### Items on the left #####

source "plugins/apple.sh"

## Adding Aerospace Spaces ##
#https://nikitabobko.github.io/AeroSpace/goodies#show-aerospace-workspaces-in-sketchybar

sketchybar --add event aerospace_workspace_change

for sid in $(aerospace list-workspaces --all); do
  monitor=$(aerospace list-windows --workspace "$sid" --format "%{monitor-appkit-nsscreen-screens-id}")

  if [ -z "$monitor" ]; then
    monitor="1"
  fi

  sketchybar --add item "space.$sid" left \
    --subscribe "space.$sid" aerospace_workspace_change \
    --set "space.$sid" \
    display="$monitor" \
    background.corner_radius=5 \
    background.height=20 \
    background.drawing=off \
    icon="$sid" \
    label.font="sketchybar-app-font:Regular:14.0" \
    label.padding_right=10 \
    label.y_offset=-1 \
    click_script="aerospace workspace $sid" \
    script="$CONFIG_DIR/plugins/space.sh $sid"
  # script="$CONFIG_DIR/plugins/aerospace.sh $sid"
done

# https://github.com/kvndrsslr/sketchybar-app-font
sketchybar --add item space_separator left \
  --set space_separator icon="" \
  icon.padding_left=4 \
  label.drawing=off \
  background.drawing=off \
  script="$PLUGIN_DIR/space_windows.sh" \
  --subscribe space_separator space_windows_change \
  --subscribe space_separator front_app_switched \
  --subscribe space_separator aerospace_workspace_change \
  --subscribe space_separator display_change \
  --subscribe space_separator system_woke

sketchybar --add item front_app left \
  --set front_app icon.drawing=off script="$PLUGIN_DIR/front_app.sh" \
  --subscribe front_app front_app_switched

##### Items right of the *notch* #####

SPOTIFY_EVENT="com.spotify.client.PlaybackStateChanged"
POPUP_SCRIPT="sketchybar -m --set \$NAME popup.drawing=toggle"

sketchybar \
  --add item spotify.name e \
  --add event spotify_change $SPOTIFY_EVENT \
  --set spotify.name click_script="$POPUP_SCRIPT" \
  popup.horizontal=on \
  popup.align=center \
  icon.drawing=off \
  \
  --add item spotify.back popup.spotify.name \
  --set spotify.back icon="" \
  icon.font="MesloLGS NF:Bold:14.0" \
  icon.padding_left=5 \
  icon.padding_right=5 \
  script="$PLUGIN_DIR/spotify.sh" \
  label.drawing=off \
  --subscribe spotify.back mouse.clicked \
  \
  --add item spotify.play popup.spotify.name \
  --set spotify.play icon="" \
  icon.font="MesloLGS NF:Bold:14.0" \
  icon.padding_left=5 \
  icon.padding_right=5 \
  updates=on \
  label.drawing=off \
  script="$PLUGIN_DIR/spotify.sh" \
  --subscribe spotify.play mouse.clicked spotify_change \
  \
  --add item spotify.next popup.spotify.name \
  --set spotify.next icon="" \
  icon.font="MesloLGS NF:Bold:14.0" \
  icon.padding_left=5 \
  icon.padding_right=10 \
  label.drawing=off \
  script="$PLUGIN_DIR/spotify.sh" \
  --subscribe spotify.next mouse.clicked \
  \
  --add item spotify.shuffle popup.spotify.name \
  --set spotify.shuffle icon="" \
  icon.font="MesloLGS NF:Bold:20.0" \
  icon.highlight_color=0xff1DB954 \
  icon.padding_left=5 \
  icon.padding_right=5 \
  label.drawing=off \
  script="$PLUGIN_DIR/spotify.sh" \
  --subscribe spotify.shuffle mouse.clicked \
  \
  --add item spotify.repeat popup.spotify.name \
  --set spotify.repeat icon="" \
  icon.font="MesloLGS NF:Bold:20.0" \
  icon.highlight_color=0xff1DB954 \
  icon.padding_left=5 \
  icon.padding_right=5 \
  label.drawing=off \
  script="$PLUGIN_DIR/spotify.sh" \
  --subscribe spotify.repeat mouse.clicked

##### Items on the right #####

sketchybar --add item clock right \
  --set clock update_freq=10 icon= script="$PLUGIN_DIR/clock.sh" \
  --add item volume right \
  --set volume script="$PLUGIN_DIR/volume.sh" \
  --subscribe volume volume_change \
  --add item battery right \
  --set battery update_freq=120 script="$PLUGIN_DIR/battery.sh" \
  --subscribe battery system_woke power_source_change

keyboard=(
  icon=""
  script="$PLUGIN_DIR/keyboard.sh"
)

sketchybar --add item keyboard right \
  --set keyboard "${keyboard[@]}" \
  --add event keyboard_change "AppleSelectedInputSourcesChangedNotification" \
  --subscribe keyboard keyboard_change

sketchybar -m --add event bluetooth_change "com.apple.bluetooth.status" \
  \
  --add item headphones right \
  --set headphones icon="" icon.font="MesloLGS NF:Bold:20.0" \
  script="$PLUGIN_DIR/ble_headset.sh" \
  --subscribe headphones bluetooth_change

##### Force all scripts to run the first time (never do this in a script) #####
sketchybar --update
